# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Témakörök Python oktatásához
author: Csóka Márk
logo: _static/logo.png


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout: 600

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: pythonbook.tex

# Enable Plotly plots
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]

# Supress Plotly warning
    

# Bibtex extension
sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex

# Add a bibtex file so that we can create citations
bibtex_csl: _static/iso-690.csl
bibtex_reference_style: author_year
bibtex_bibfiles: references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  favicon: _static/favicon.ico